services:
  - type: web
    name: n8n
    env: docker
    region: ohio
    plan: starter
    branch: render-deployment
    dockerfilePath: ./Dockerfile
    dockerCommand: n8n start
    envVars:
      - key: NODE_ENV
        value: production
      - key: N8N_PORT
        value: "5678"
    buildFilter:
      paths:
        - Dockerfile